### ISSUE TITLE
Update deprecated postgres FloatRangeField field

### ISSUE THREAD

**Issue by jd-0001** [Hipo/drf-extra-fields#133] opened 2020-08-04 13:34 UTC
Hi,

I am using `Base64ImageField` field and I recently upgraded all of my packages and I found below error in my terminal.
```bash
  File "/xxx/serializers.py", line 1, in <module>
    from drf_extra_fields.fields import Base64ImageField
  File "/xxx/env/lib/python3.6/site-packages/drf_extra_fields/fields.py", line 256, in <module>
    ModelSerializer.serializer_field_mapping[postgres_fields.FloatRangeField] = FloatRangeField
AttributeError: module 'django.contrib.postgres.fields' has no attribute 'FloatRangeField'
```

Packages:
```bash
django-extra-fields    2.0.5

Django                 3.1
django-appconf         1.0.4
django-braces          1.14.0
djangorestframework    3.11.0
```

Let me know if I am missing any other packages to list out.

Do I need to use outdated packages for now or I can resolve it easily???

**Comment by MarcoGlauser** [comment] 2020-08-05 09:18
Our CI caught the same issue when it tried to upgrade to Django 3.1.
FloatRangeField was deprecated in Django 2.2 and was replaced by the DecimalRangeField.

**Comment by alicertel** [comment] 2020-08-05 14:07
There is an active PR https://github.com/Hipo/drf-extra-fields/pull/132. Once the issue is resolved i will take a new release.

**Comment by alicertel** [comment] 2020-08-07 09:23
This is fixed with the latest release. Please see the [release notes.](https://github.com/Hipo/drf-extra-fields/releases/tag/v3.0.0)

**Closed by alicertel** 2020-08-07 09:23 UTC

**Comment by MarcoGlauser** [comment] 2020-08-07 09:44
Awesome, works on our CI! Thank you for the quick response :)
