### ISSUE TITLE
{picture: ["Please upload a valid image."]}

### ISSUE THREAD

**Issue by juliocebrito** [Hipo/drf-extra-fields#22] opened 2016-05-24 05:43 UTC
Hi friend, i am using Base64ImageField it is working nice i can read, create and delete but when i try to Update the model this show me this error.

PUT http://xxxxxxx 400 (Bad Request)
{picture: ["Please upload a valid image."]}
## """model"""

class Product(models.Model):
category = models.CharField(max_length=255)
type = models.CharField(max_length=255)
name = models.CharField(max_length=255)
description = models.TextField()
price = models.DecimalField(max_digits=12, decimal_places=2)
quantity = models.IntegerField()
stock = models.BooleanField(default=False)
picture = models.ImageField(upload_to='product/picture', blank=True, null=True)
created = models.DateTimeField(auto_now_add=True, auto_now=False)
updated = models.DateTimeField(auto_now_add=False, auto_now=True)
## """Serializer"""

class ProductSerializer(serializers.HyperlinkedModelSerializer):
picture = Base64ImageField(required=False)
class Meta:
model = Product
fields = ('id', 'stock', 'category', 'type', 'name', 'price', 'quantity', 'picture', 'url')
## """ViewSet"""

class ProductViewSet(viewsets.ModelViewSet):
queryset = Product.objects.all()
serializer_class = ProductSerializer

Please Help me.

**Comment by yigitguler** [comment] 2016-05-24 13:34
Hello,

The view looks fine. Can you please send the the request that gives error?

Are you sending a new image or sending an empty image? First 2 lines of the base64 image will be enough.

**Comment by juliocebrito** [comment] 2016-05-25 01:20
Hello,
 the error is just here in Base64ImageField when i try to update

            # Try to decode the file. Return validation error if it fails.
            try:
                decoded_file = base64.b64decode(base64_data)
            except (TypeError, binascii.Error):
                raise ValidationError(_("Please upload a valid image."))

when i send a new image there is no problem, the problem is when i try to update:

category = models.CharField(max_length=255)
type = models.CharField(max_length=255)
name = models.CharField(max_length=255)
description = models.TextField()
price = models.DecimalField(max_digits=12, decimal_places=2)
quantity = models.IntegerField()
stock = models.BooleanField(default=False)

**Comment by yigitguler** [comment] 2016-05-25 04:32
Hi,

This means that the image of the PATCH request is not valid.

We might try to regenerate the issue if you send us the base64 image.

**Comment by juliocebrito** [comment] 2016-05-25 17:28
Hi, django ImageField does not save a base64 image it save a image "xxxxx.jpg"

**Comment by yigitguler** [comment] 2016-05-25 18:15
@juliocebrito we are using this package in every project and it is working fine. There must be a problem with the request itself. Can you paste the REQUEST that results error?

**Comment by vaibhav-jain** [comment] 2016-07-25 17:26
Hey @yigitguler any update about this issue???

 I am facing this issue too. If I upload new image then its fine but if I try to submit data without changing anything then I get same error. 

Reason is the `GET` request has image as URL `"photo":"https://localhost:8000/photos/542c130b-169.jpg"` so when I try to send `PATCH` request I get `Invalid image error`. As it accepts `base64 string` can you tell me how to solve this . . . .

**Comment by yigitguler** [comment] 2016-07-25 21:19
Hi @vaibhav-jain,

As far as I understand, you are trying to patch the field with this URL. Am I correct? 

If that's the case, it is the expected behaviour. You should only patch the fields that are changed. If the field is changed, send the new image in base64 format. Otherwise do not send the image at all.  

If you have a solution proposition, it is more than welcome. Just open a PR.

**Comment by vaibhav-jain** [comment] 2016-07-26 05:47
HI @yigitguler thanks for the tip . . . . now its working as expected.

**Comment by sehmaschine** [comment] 2016-10-12 15:48
I might be missing something, but I don't fully agree with the proposed solution here. IMO, if I get data from an API and send the exact same data back to that API, no update should happen. But that´s not the case with the current implementation. Besides, the solution mentioned above (only patching the updated fields) does not solve the issue with using PUT.

**Comment by yigitguler** [comment] 2016-10-12 19:07
>  if I get data from an API and send the exact same data back to that API, no update should happen.

I totally agree. This is mostly a problem in PUT requests. Do you have a solution to this problem?

**Comment by sehmaschine** [comment] 2016-10-13 09:18
Theoretically speaking: if data is not base64, just return the value with `to_internal_value` ...

```
if ';base64,' in base64_data:
    header, base64_data = base64_data.split(';base64,')
else:
    return base64_data
```

But it does not work with the current implementation of `to_representation`:

```
return super(Base64FieldMixin, self).to_representation(file)
```

The code above returns the full path including the host and media folder (with the DRF default settings). Therefore, the database will still be updated since base64_data does not match what´s been stored.

Example:

1. Database is empty. I add a new file (filename test.jpg).
2. Upload works fine. Database now contains `upload_folder/test.jpg`.
3. But the API response contains `http://myhost.com/media/upload_folder/test.jpg`.
4. If I send this value, the database gets updated again.

If I change the DRF settings to ...

```
REST_FRAMEWORK = {
    'UPLOADED_FILES_USE_URL': False,
    ...
}
```

... the API response contains the exact same value as the database and everyhing works fine.

Essentially, a more bullet-proof solution would be this:

```
if ';base64,' in base64_data:
    header, base64_data = base64_data.split(';base64,')
else:
    # we need to return what´s been stored with the DB, so if
    # UPLOADED_FILES_USE_URL is true, we have to change
    # base64_data to a relative path
    return base64_data
```

**Comment by yigitguler** [comment] 2016-10-16 10:14
I agree, the system should just ignore if the client sends the existing file (with or without the domain depending the settings of the project) 

However, if the client sends another URL or path, the backend should throw an error since it only accepts a base64 input. 

I will implement this when I find some time. Or if anyone interested can chime in, we will be happy to approve.

**Comment by mirzadelic** [comment] 2019-05-31 15:32
Any news about this?

**Comment by sshishov** [comment] 2019-06-08 07:26
Any updates here?
The best way solution would be to support URLs as well as base64 data and make an update ONLY if image is changed. But to support URLs, the image from url should be downloaded first and it is out of scope as need to use 3rd party library to download it (or `urllib/urllib3` at least).
Currently it is impossible to use this field without adding workarounds either on FE side or BE side.

**Comment by alicertel** [comment] 2019-06-20 11:18
@sshishov what you suggested is another field. It's not in the scope of Base64ImageField. It migt be useful to add another field like RemoteImageField. PRs welcome :)

@sehmaschine i don’t think there is any requirement in rest apis that the response of a GET should be PUTable. In this case API accepts an image file but presents it as string(url). Input and output format is different.

If you use DRF's image field and don't provide a valid image, it will raise error. Base64ImageField works exactly same. If you don't provide a valid base64 image it raises error.

**Closed** 2020-04-16 13:17 UTC

**Comment by oesah** [comment] 2025-01-06 16:34
Very late to the party, but I handled it like this:

```python
    def run_validation(self, data=serializers.empty):
        if data.get("user_photo") and not data.get("user_photo").startswith("data:image"):
            data.pop("user_photo")

        return super().run_validation(data)
```
