### ISSUE TITLE
Unable to make the ImageField as required in Swagger POST API

### ISSUE THREAD

**Issue by MounikaKommineni** [Hipo/drf-extra-fields#66] opened 2019-01-21 12:02 UTC
My model:
```
class Image(models.Model):
      image=models.ImageField(upload_to='photos')
      name=models.CharField(max_length=40,unique=False)
```
My serializer:
```
class imagesSerializer(serializers.ModelSerializer):
      image = Base64ImageField(required=True)
      class Meta:
         model = Image
         fields = ('id','name','image')
```
My swagger view:
![kfrof](https://user-images.githubusercontent.com/46343336/51473453-6cdf6d00-1da2-11e9-9b32-104418ccbb36.png)

How to make the imagefield as required in swagger post request ?

**Comment by johnthagen** [comment] 2019-03-04 22:02
I noticed this too in generated Angular TypeScript. The image variables were always marked with `?`, meaning they were optional.

**Comment by shafiyal** [comment] 2019-03-11 08:48
I am also facing the same issue even though i specified required=True in serializer class

**Comment by baranugur** [comment] 2019-03-15 10:18
I'm using the same serializer setup and mine seems to be working fine. Maybe this is an issue of differences in versions. Here are the versions of Django, Django Extra Fields, Django REST Framework and Django REST Swagger that I have used, so you can compare: `Django==2.1.7`, `django-extra-fields==1.0.0`, `djangorestframework==3.9.2`, `django-rest-swagger==2.2.0`.

![swagger_correct](https://user-images.githubusercontent.com/33009014/54424509-1a785800-4724-11e9-912c-deb9b128869b.png)

**Comment by johnthagen** [comment] 2019-03-15 11:46
I wonder if it's because of the `readOnly` property? Would a `readOnly` property make it optional because it's not required when writing to the API? Is this because of how the file is normally returned as a URL rather than the data directly? (I'm just spit balling at this point).

**Comment by baranugur** [comment] 2019-03-15 14:26
ReadOnly fields cannot be required at the same time, therefore it's not possible to have a field where both `required` and `read_only` are set to `True` in the latest version of Django REST Framework.

**Comment by johnthagen** [comment] 2019-03-15 15:37
What's weird is in my case, I never set `read_only` to `True`. The serializer is a [`WritableNestedSerializer`](https://github.com/beda-software/drf-writable-nested), but I don't see how that would affect the field.

**Comment by baranugur** [comment] 2019-03-18 15:07
I've used the serializer below:

```
class ImageSerializer(WritableNestedModelSerializer):
    image = Base64ImageField(required=True)

    class Meta:
        model = Image
        fields = ('id', 'name', 'image')
```

It still seems to be working fine.

![swagger](https://user-images.githubusercontent.com/33009014/54540096-6a675100-49a8-11e9-8001-7ef93c405582.png)

**Comment by johnthagen** [comment] 2019-03-18 16:16
@baranugur Could you also post your `Image` `Model`?

I wonder why your `image` field doesn't say `string($uri)`. That is how mine always is (and the OP's).

**Comment by baranugur** [comment] 2019-03-19 10:15
The model that I've created is identical to OP's.

I think `drf-yasg==1.13.0` is causing the problem here. I've just tried it with `Base64ImageField` and then I've used the built-in `serializers.ImageField`; this is what I've gotten in both cases:

![yasg](https://user-images.githubusercontent.com/33009014/54596472-c7fdab00-4a45-11e9-8ab8-134f2111089a.png)

**Comment by johnthagen** [comment] 2019-03-19 11:11
Cross posted to https://github.com/axnsan12/drf-yasg/issues/332

**Comment by johnthagen** [comment] 2019-03-19 14:21
Confirmed this is `drf-yasg` specific (intended) behavior:

https://github.com/axnsan12/drf-yasg/issues/332#issuecomment-474344322

> That is indeed the case. The field you linked breaks the contract of FileField by making it accept a string instead of an UploadedFile.
> 
> You can work around this with a custom FieldInspector that returns an appropriate Schema object of type string, which should be placed before the FileFieldInspector.

**Comment by yigitguler** [comment] 2019-04-18 11:50
Marking as completed.

**Comment by johnthagen** [comment] 2019-04-18 11:52
@yigitguler There may be a way to work around this (at least in documentation): https://github.com/axnsan12/drf-yasg/issues/332#issuecomment-474344322

I don't quite understand what needs to be done, but if this issue were left open it might be useful. We may be able to at least document how to make this work with `drf-yasg`, which I think would be valuable.

Do you happen to understand the comment in the link above, and how we could fix it?

**Comment by yigitguler** [comment] 2019-04-18 12:00
We can reopen the issue. However, I think there is nothing we can do to fix this situation. Developers of drf-yasg _assumed_ that only multipart requests can contain files. Which is not true for our use case.

**Comment by johnthagen** [comment] 2019-07-03 16:46
Using [Custom Schema Generation](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html) may be a method to solve this.

**Comment by WasinTh** [comment] 2019-08-21 14:17
Hi! This is the work around code that I've overridden **FieldInspector** to mark Base64ImageField, Base64FileField, Base64FieldMixin as required field
NOTE: I've to remove format from the String because the POST, PUT, PATCH... method use SchemaRef which reference the schema from GET method.

```
from drf_yasg.inspectors import FieldInspector, SwaggerAutoSchema
from drf_yasg.app_settings import swagger_settings


class Base64FileFieldInspector(FieldInspector):
    BASE_64_FIELDS = ['Base64ImageField', 'Base64FileField', 'Base64FieldMixin']

    def process_result(self, result, method_name, obj, **kwargs):
        if isinstance(result, openapi.Schema) and \
                obj.__class__.__name__ in Base64FileFieldInspector.BASE_64_FIELDS:
            schema = openapi.resolve_ref(result, self.components)
            schema.pop('readOnly', None)
            schema.pop('format', None)  # Remove $url format from string

        return result


class Base64FileAutoSchema(SwaggerAutoSchema):
    field_inspectors = [Base64FileFieldInspector] + swagger_settings.DEFAULT_FIELD_INSPECTORS


class FormAttachmentViewSet(viewsets.ModelViewSet):
    queryset = .......
    serializer_class = ..........
    swagger_schema = Base64FileAutoSchema
```
Result:
<img width="267" alt="Screen Shot 2562-08-21 at 21 15 39" src="https://user-images.githubusercontent.com/12245851/63439829-fb12f300-c458-11e9-9635-a14d1939043f.png">

**Comment by johnthagen** [comment] 2019-08-21 17:07
@WasinTh Looks pretty neat -- would you mind opening a PR to this repo's README? I think it would be good to document this for others and for others to test out.

**Comment by WasinTh** [comment] 2019-08-23 06:51
@johnthagen  sure this is the pull request on README.md file
https://github.com/Hipo/drf-extra-fields/pull/100

**Comment by zengzhengrong** [comment] 2020-05-02 03:02
How about make it some example code to testprojet, this repo example does not have about flieupload or imageupload,it would be make good to use

**Comment by ilmesi** [comment] 2020-05-11 14:54
In Swagger API, I'm using the following setup to show to field as required without any problems:
```
class PDFBase64FileField(Base64FileField):
    ALLOWED_TYPES = ['pdf']

    class Meta:
        swagger_schema_fields = {
            'type': 'string',
            'title': 'File Content',
            'description': 'Content of the file base64 encoded',
            'read_only': False  # <-- FIX
        }

    def get_file_extension(self, filename, decoded_file):
        try:
            PyPDF2.PdfFileReader(io.BytesIO(decoded_file))
        except PyPDF2.utils.PdfReadError as e:
            logger.warning(e)
        else:
            return 'pdf'
```

And to use "string" format instead of an URL, you will to create the field with use_url=False.

**Comment by alicertel** [comment] 2020-05-11 15:04
@ilmesi  Thank you for the suggestion. This seems pretty simple to me compered to creating a FieldInspector. What do you think @WasinTh ?

**Comment by ilmesi** [comment] 2020-05-11 20:49
@alicertel No problem! I got it from the code at `FieldInspector.add_manual_fields` from yasg. It seems to work pretty well and it's less work than creating a new FieldInspector..

**Comment by johnthagen** [comment] 2020-05-26 15:31
I can confirm that @ilmesi's answer works. It seems like the most ideal work-around thus far.

**Comment by WasinTh** [comment] 2020-05-27 01:54
> @ilmesi Thank you for the suggestion. This seems pretty simple to me compered to creating a FieldInspector. What do you think @WasinTh ?

Agreed. The solution to override Base64FileField is much more simple.

**Comment by alicertel** [comment] 2020-08-06 14:31
@WasinTh Would you like to update your PR https://github.com/Hipo/drf-extra-fields/pull/100 with the suggested solution https://github.com/Hipo/drf-extra-fields/issues/66#issuecomment-626755554 ?

**Comment by WasinTh** [comment] 2020-08-14 02:09
> @WasinTh Would you like to update your PR #100 with the suggested solution [#66 (comment)](https://github.com/Hipo/drf-extra-fields/issues/66#issuecomment-626755554) ?

Sure. I've pushed the updated answer on those PRs.

**Comment by alicertel** [comment] 2020-08-14 06:15
Thanks @WasinTh

**Closed by alicertel** 2020-08-14 06:15 UTC

**Comment by Hassanzadeh-sd** [comment] 2020-11-25 07:38
you should change your parser like this :

```
    from rest_framework import permissions, viewsets
    from rest_framework.mixins import (CreateModelMixin, DestroyModelMixin,
                                       ListModelMixin, RetrieveModelMixin)
    from rest_framework.parsers import FormParser, MultiPartParser
    from .models import Customer
    from .permissions import CustomerPermission
    from .serializer import CustomerSerializer
    
    
    class CustomerViewSet(CreateModelMixin, ListModelMixin, RetrieveModelMixin, 
                          DestroyModelMixin, viewsets.GenericViewSet):
        permission_classes = [CustomerPermission]
        queryset = Customer.objects.all()
        serializer_class = CustomerSerializer
        parser_classes = (FormParser, MultiPartParser)
```

after that you can check your swagger :

![image](https://user-images.githubusercontent.com/32982356/100196715-8574bd00-2f0e-11eb-9acb-8ebc0299a2e6.png)

I hope this can help you

**Comment by Krzyzaku21** [comment] 2022-01-13 15:53
If you want create no class views but use drf:
`register_parameters = [openapi.Parameter(
    'date_of_birth', in_=openapi.IN_FORM, description='Add date like 2000-12-12', type=openapi.FORMAT_DATE,
    required=True)]


@swagger_auto_schema(methods=['post'], request_body=RegisterSerializer, manual_parameters=register_parameters)
@ api_view(['POST', ])
@ parser_classes([parsers.MultiPartParser, parsers.FormParser])
def user_register_serializer(request):
    if request.method == 'POST':
        new_data = {
            'response': f"Email send to {request.data['email']}",
        }
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            new_data.update(serializer.data)
            new_data.pop('password')
            serializer.save()
            user_email_send(request)
        else:
            new_data = serializer.errors
        return Response(new_data)
`
using manual_parameters you can override form in swagger and add new functions like default etc to image.

**Comment by mortgage40** [comment] 2025-01-31 08:08
> [@WasinTh](https://github.com/WasinTh) Would you like to update your PR [#100](https://github.com/Hipo/drf-extra-fields/pull/100) with the suggested solution [#66 (comment)](https://github.com/Hipo/drf-extra-fields/issues/66#issuecomment-626755554) ?





https://stackdev.space/questions/updating-imagefield-or-filefield-in-djangorestframework-a-step-by-step-guide
